PaGlobal_MaidList_All = {
  _ui = {
    stc_title = nil,
    txt_noMaidFound = nil,
    txt_maidCount = nil,
    txt_maidCountValue = nil,
    stc_maidListTopBg = nil,
    list2_maid = nil,
    stc_listBg = nil,
    stc_tabBar = nil,
    stc_tabBarLine = nil,
    chk_UseMultiMaid = nil,
    txt_UseMultiMaid = nil,
    chk_UseMaidActor = nil,
    chk_FollowMaidActor = nil,
    stc_maidActor_buttonBg = nil,
    stc_maidActor_leftBg = nil,
    stc_maidActor_rightBg = nil,
    stc_maidActor_photoEmpty = nil,
    stc_maidActor_photo = nil,
    txt_maidActor_name = nil,
    btn_maidActor_regist = nil,
    btn_maidActor_customize = nil,
    btn_maidActor_dye = nil,
    btn_maidActor_action = nil,
    chk_maidActor_underwearIndivisual = nil,
    chk_maidActor_helmIndivisual = nil,
    chk_maidActor_helmOpen = nil,
    chk_maidActor_cloakIndivisual = nil,
    chk_maidActor_subWeaponIndivisual = nil,
    stc_maidActor_equipHide = nil,
    stc_maidActor_guideIcon = nil
  },
  _ui_pc = {
    btn_close = nil,
    stc_tabBg = nil,
    btn_radios = {},
    btn_warehouse = nil,
    btn_market = nil,
    btn_marketPlace = nil,
    btn_pcRoom = nil,
    btn_ScaleResize = nil,
    btn_summonMaidActor = nil,
    btn_unsummonMaidActor = nil,
    btn_maidActorManagement = nil
  },
  _ui_console = {
    stc_tabBg = nil,
    rdo_tabs = {},
    stc_keyGuideLB = nil,
    stc_keyGuideRB = nil,
    stc_keyGuideAreaBg = nil,
    stc_guideIconY = nil,
    stc_guideIconLS = nil,
    stc_guideIconB = nil,
    stc_guideIconX = nil,
    stc_guideIconLTX = nil,
    stc_guideIconLTY = nil,
    stc_guideIconRTX = nil,
    stc_guideIconRTY = nil,
    stc_guideIconRS = nil
  },
  _slotConfig = {
    createIcon = false,
    createBorder = true,
    createCount = true,
    createCash = true,
    createMaidActorOnly = true,
    createExpiration = true,
    createExpirationBG = true,
    createClassEquipBG = true,
    createEnduranceIcon = true,
    createItemLock = true,
    createBlack = true,
    createEnchant = true,
    createBadBG = true
  },
  _slotNoId = {
    [14] = "Static_Slot_Avatar_Chest",
    [15] = "Static_Slot_Avatar_Gloves",
    [16] = "Static_Slot_Avatar_Boots",
    [17] = "Static_Slot_Avatar_Helm",
    [18] = "Static_Slot_Avatar_RightHand",
    [19] = "Static_Slot_Avatar_LeftHand",
    [30] = "Static_Slot_Avatar_AwakenWeapon",
    [20] = "Static_Slot_Avatar_UnderWear",
    [21] = "Static_Slot_FaceDecoration1",
    [22] = "Static_Slot_FaceDecoration2",
    [23] = "Static_Slot_FaceDecoration3",
    [45] = "Static_Slot_Back"
  },
  _slotNoIdToString = {
    [__eEquipSlotNoAvatarChest] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_BODY"),
    [__eEquipSlotNoAvatarGlove] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_HANDS"),
    [__eEquipSlotNoAvatarBoots] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_BOOTS"),
    [__eEquipSlotNoAvatarHelm] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_HELM"),
    [__eEquipSlotNoAvatarWeapon] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_MAIN"),
    [__eEquipSlotNoAvatarSubWeapon] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_SUB"),
    [__eEquipSlotNoAvatarAwakenWeapon] = PAGetString(Defines.StringSheet_GAME, "Lua_EquipSlotNo_String_avatarAwakenWeapon"),
    [__eEquipSlotNoAvatarUnderwear] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_UNDERWEAR"),
    [__eEquipSlotNoFaceDecoration1] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_HEAD"),
    [__eEquipSlotNoFaceDecoration2] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_EYES"),
    [__eEquipSlotNoFaceDecoration3] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_MOUSE"),
    [__eEquipSlotNoTemp] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_BACK")
  },
  slots = {},
  slotBGs = {},
  _extendedSlotInfoArray = {},
  _EquipNoMin = __eEquipSlotNoRightHand,
  _EquipNoMax = __eEquipSlotNoCount,
  _maidActorEquipSlot_UnderWearSpanX = 0,
  _maidActorEquipSlot_UnderWearSpanY = 0,
  _eTAB_TYPE = {
    ALL = 1,
    STORAGE = 2,
    MARKETPLACE = 3,
    MARKET = 4,
    MAIDACTOR = 5,
    COUNT = 6
  },
  _currentTab = 1,
  _maidData = nil,
  _isConsole = false,
  _initialize = false,
  _panelOpenPosX = nil,
  _panelOpenPosY = nil,
  _panelOriginSizeY = nil,
  _dontGoMaid = -1,
  _maidType = -1
}
runLua("UI_Data/Script/Widget/Maid/Panel_Window_MaidList_All_1.lua")
runLua("UI_Data/Script/Widget/Maid/Panel_Window_MaidList_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_PaGlobal_MaidList_All_Init")
function FromClient_PaGlobal_MaidList_All_Init()
  PaGlobal_MaidList_All:initialize()
end
