PaGlobal_PalaceManagement_Node = {
  _ui = {
    st_Title = nil,
    btn_Close = nil,
    st_NodeBg = nil,
    st_NodeName = nil,
    st_NodeDesc = nil,
    btn_Node = nil,
    st_nodeBG = nil,
    st_Working = nil,
    st_WorkerTitle = nil,
    st_WorkerEmpty = nil,
    st_WorkerImg = nil,
    st_WorkerText = nil,
    st_ActProgressBG = nil,
    st_ActProgress = nil,
    txt_ActProgressText = nil,
    st_ProgressBG = nil,
    st_Progress = nil,
    txt_WorkerName = nil,
    txt_ProgressText = nil,
    btn_WorkStop = nil,
    st_MainBg = nil,
    st_ItemListTitle = nil,
    btn_ChangeBoard = nil,
    btn_RestartWork = nil,
    btn_Warehouse = nil,
    btn_Navi = nil,
    st_NpcName = nil,
    st_LeftCount = nil,
    txt_Count = nil,
    st_MouseRBtn = nil,
    txt_RClick = nil,
    st_MaterialBg = nil,
    txt_MaterialTitle = nil,
    st_MaterialItemSlot = {},
    txt_MaterialName = {},
    txt_MaterialCount = {},
    txt_ConsoleUI_RT = nil
  },
  _boardGroupKey = 0,
  _boardGroupName = "",
  _currentSelectBoardIndex = 0,
  _initialize = false,
  _boardCount = 0,
  _workerNo = 0,
  _maxItemCount = 10,
  _maxBoardCount = 6,
  _maxMaterialItemCount = 5,
  _board = {},
  _materialSlot = {},
  _slotConfig = {
    createIcon = true,
    createBorder = true,
    createCount = true,
    createCash = false,
    createEnchant = true,
    createEnduranceIcon = false,
    createOriginalForDuel = false
  },
  _characterKey = 0,
  _dialogIndex = 0,
  _boardGroupType = __eePalaceManageType_Count,
  _freeRerollCount = 0,
  _warehouseRegionKey = 1853,
  _isShowConsoleItemTooltip = false,
  _consoleItemTooltipKey = 0,
  _tooltipDesc = "",
  _isOnProbabilityToolTip = false,
  _showMaterialsItemIndex = 0,
  _showMaterialsBoardKey = 0
}
runLua("UI_Data/Script/Window/PalaceManagement/Panel_Window_PalaceManagement_Node_1.lua")
runLua("UI_Data/Script/Window/PalaceManagement/Panel_Window_PalaceManagement_Node_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_PalaceMangement_Node_Init")
function FromClient_PalaceMangement_Node_Init()
  PaGlobal_PalaceManagement_Node:initialize()
end
