PaGlobal_SkillGroup_All = {
  _ui = {
    _stc_skillTypeArea = nil,
    _rdo_successionSkill = nil,
    _rdo_awakenSkill = nil,
    _stc_successionLock = nil,
    _stc_awakenLock = nil,
    _stc_radioGroup = nil,
    _rdo_tab_mainWeapon = nil,
    _rdo_tab_awakenWeapon = nil,
    _rdo_tab_fusioneningSkill = nil,
    _rdo_tab_upgradeSkill = nil,
    _stc_selectLine = nil,
    _stc_topFunctionArea = nil,
    _edit_search = nil,
    _btn_search = nil,
    _stc_skillPoint = nil,
    _txt_skillPointTitle = nil,
    _txt_skillPointTitleText = nil,
    _txt_skillPointValue = nil,
    _btn_allReset = nil,
    _btn_skillSet = nil,
    _btn_filter = nil,
    _stc_mainWeaponSkillArea = nil,
    _frame_skillGroupArea_main = nil,
    _scroll_skillGroupArea_main = nil,
    _stc_awakenSkillArea = nil,
    _frame_skillGroupArea_awaken = nil,
    _scroll_skillGroupArea_awaken = nil,
    _stc_fusionSkillArea = nil,
    _frame_fusionSkill = nil,
    _scroll_skillGroupArea_fusionSkill = nil,
    _stc_upgradeSkillArea = nil,
    _list2_upgradeList = nil,
    _btn_naviSkillMaster = nil,
    _stc_bottomArea = nil,
    _btn_movie = nil,
    _btn_showOtherCharSkill = nil,
    _combo_skillSetting = nil,
    _chk_playShow = nil,
    _stc_presetBG = nil,
    _rdo_preset_templete = nil,
    _btn_lock_templete = nil,
    _btn_presetSave = nil,
    _stc_shiftGuideMain = nil,
    _btn_shiftGuideClose = nil,
    _keyguide_naviSkillMaster = nil,
    _keyguide_Bg = nil,
    _keyguide_CameraBg = nil,
    _keyguide_A = nil,
    _keyguide_B = nil,
    _keyguide_X = nil,
    _keyguide_Y = nil,
    _keyguide_LB = nil,
    _keyguide_RB = nil,
    _keyguide_LS = nil,
    _keyguide_LT_A = nil,
    _keyguide_LT_X = nil,
    _keyGuide_LT_X_sub = nil,
    _keyguide_LT_Y = nil,
    _keyguide_LT_DPad = nil,
    _keyguide_RT_X = nil,
    _keyguide_RT_Y = nil,
    _templeteList = nil,
    _stc_templete_skillGroup = nil,
    _rdo_templete_skillSubGroup = nil,
    _stc_templete_lineControl = nil,
    _stc_templete_fusionSkill = nil,
    _stc_templete_fusionSkillResult = nil
  },
  _line_maxCount = 11,
  _skillGroupPool_main = {},
  _skillSubGroupPool_main = {},
  _lineAPool_main = {},
  _lineCPool_main = {},
  _skillGroupPool_awaken = {},
  _skillSubGroupPool_awaken = {},
  _lineAPool_awaken = {},
  _lineCPool_awaken = {},
  _fusionSkillPool = {},
  _fusionSkillResultPool = {},
  _btn_skillPresetList = {},
  _btn_skillPresetLockList = {},
  _skillGroupPool_maxCount_main = 100,
  _skillSubGroupPool_maxCount_main = 4,
  _lineAPool_maxCount_main = {
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10
  },
  _lineCPool_maxCount_main = {
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10
  },
  _skillGroupPool_maxCount_awaken = 50,
  _skillSubGroupPool_maxCount_awaken = 2,
  _lineAPool_maxCount_awaken = {
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10
  },
  _lineCPool_maxCount_awaken = {
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10
  },
  _fusionSkillPool_maxCount = 3,
  _skillGroupPool_index_main = 0,
  _skillSubGroupPool_index_main = 0,
  _lineAPool_index_main = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  },
  _lineCPool_index_main = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  },
  _skillGroupPool_index_awaken = 0,
  _skillSubGroupPool_index_awaken = 0,
  _lineAPool_index_awaken = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  },
  _lineCPool_index_awaken = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  },
  _fusionSkillPool_index = 0,
  _fusionSkillResultPool_index = 0,
  _btn_skillPresetList = {},
  _btn_skillPresetLockList = {},
  _skillSubGroupInfo = {},
  _skillGroupInfo = {},
  _lineInfo = {},
  _fusionSkillInfo = {},
  _fusionSkillResultInfo = {},
  _searchSkillGroupInfo = {},
  _searchFusionSkillInfo = {},
  _ePoolType = {
    _skillGroup_main = 0,
    _subSkillGroup_main = 1,
    _lineA_main = 2,
    _lineC_main = 3,
    _skillGroup_awaken = 4,
    _subSkillGroup_awaken = 5,
    _lineA_awaken = 6,
    _lineC_awaken = 7,
    _fusionSkill = 8,
    _fusionSkillResult = 9,
    _count = 10
  },
  _eTabType = {
    _mainWeapon = 0,
    _awaken = 1,
    _fusion = 2,
    _upgrade = 3
  },
  _tabList = {},
  _slotConfig = {createIcon = true},
  _eSkillShowTypeIndex = {
    _baseSkill = 0,
    _blackSpiritSkill = 1,
    _linkSkill = 2
  },
  _selectedBranch = 0,
  _canSelectBranch = false,
  _selectedTab = -1,
  _isOpenFusionSkill = false,
  _isOpenUpgradeSkill = false,
  _targetSkillType = -1,
  _selectedSkillType = __eSkillTypeParam_Normal,
  _selectedSkillNo = 0,
  _selectedSkillGroupKey = 0,
  _isLearnedSuccessionSkill = false,
  _isLearnedAwakenSkill = false,
  _clearSkillGroupKey = 0,
  _isClearSkillFusion = false,
  _fusionSkillEffectPlay = false,
  _fusionSkillEffectTime = 0,
  _mainSkillNo = 0,
  _subSkillNo = 0,
  _resultSkillNo = 0,
  _selectedFusionSlotNo = 0,
  _selectedFusionSkillIndex = 0,
  _maxFusionSkillCount = 0,
  _upgradeIndex = 0,
  _isEditMode = false,
  _isAwakenGuide = false,
  _isWindow = false,
  _remainSkillPoint = 0,
  _isDialog = false,
  _isDraggingFromTree = false,
  _filterText = nil,
  _filterIndex = -1,
  _filterFusionIndex = -1,
  _filterFusionSkillIndex = 0,
  _curAlignType = -1,
  _originSkillPointValuePosX = 0,
  _originSkillPointSizeX = 0,
  _isShowStaminaPanel = false,
  _showAni = true,
  _isPadSnapping = false,
  _initialize = false
}
runLua("UI_Data/Script/Window/Skill/Panel_Window_SkillGroup_All_1.lua")
runLua("UI_Data/Script/Window/Skill/Panel_Window_SkillGroup_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_SkillGroup_All_Init")
function FromClient_SkillGroup_All_Init()
  PaGlobal_SkillGroup_All:initialize()
end
