PaGlobal_Solrare_Matching = {
  _ui = {
    _btn_Close = nil,
    _btn_Wiki = nil,
    _stc_RankIcon = nil,
    _txt_Tier = nil,
    _txt_RankRating = nil,
    _stc_ClassIcon = nil,
    _txt_Level = nil,
    _txt_Name = nil,
    _txt_Ranking = nil,
    _txt_RecentRecord = nil,
    _btn_CopyUserInformation = nil,
    _stc_copyProgress = nil,
    _stc_changeModeBg = nil,
    _btn_changeMode = nil,
    _btn_RankGameReq = nil,
    _btn_NormalGameReq = nil,
    _txt_NoRecord = nil,
    _frameContent = nil,
    _frameRecentInfoList = nil,
    _frameVertiScroll = nil,
    _stc_matchingBg = nil,
    _txt_MatchingState = nil,
    _stc_TierListBg = nil,
    _btn_MatchingCancel = nil,
    _btn_Equip = nil,
    _btn_CeremonyOption = nil,
    _btn_TierList = nil,
    _btn_Rules = nil,
    _txt_TierListTable = {},
    _txt_MatchingElapsedTime = nil,
    _btn_Ranking = nil,
    _btn_ReplayList = nil,
    _btn_SolarePass = nil,
    _btn_CoinShop = nil,
    _placementBg = nil,
    _placementRecordIcon = Array.new(),
    _keypadBg = nil,
    _keypadX = nil,
    _keypadA = nil,
    _keypadB = nil,
    _keypadY = nil
  },
  _frameControlList = Array.new(),
  _recordNumberList = Array.new(),
  _recentInfoList = {},
  _recentInfoCount = 0,
  _maxShowRecentInfoCount = 20,
  _selectedRecentRecordIndex = -1,
  _normalBgSize = 0,
  _detailBgSize = 0,
  _matchingDelayTime = 2,
  _matchingTime = 0,
  _matchingCloseTime = 0,
  _maxTierCount = 21,
  _currentDeltaTime = 0,
  _currentElapsedTime = 0,
  _currentSelectMode = __ePVPArenaMode_SOLARE3vs3,
  _placementMatchMaxCount_1vs1 = ToClient_GetSolarePlaceMentMatchCount(__ePVPArenaMode_SOLARE1vs1),
  _placementMatchMaxCount_3vs3 = ToClient_GetSolarePlaceMentMatchCount(__ePVPArenaMode_SOLARE3vs3),
  _copyUserInformationWaitTime = 20,
  _startWinStreakCount = ToClient_GetSolareWinningCount(),
  _middleButtonList = {},
  _initialize = false
}
runLua("UI_Data/Script/Window/Solrare/Panel_Solrare_Matching_1.lua")
runLua("UI_Data/Script/Window/Solrare/Panel_Solrare_Matching_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_Solrare_Matching_Init")
function FromClient_Solrare_Matching_Init()
  PaGlobal_Solrare_Matching:initialize()
end
